# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "dev"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform int/uat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: trstringer/manual-approval@v1
        name: Wait for approval
        with:
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1

      - name: Run a one-line script
        if: github.ref == 'refs/heads/"main"'
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${GITHUB_REF}

  terraform-prod:
    runs-on: ubuntu-latest
    name: Terraform prod
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: trstringer/manual-approval@v1
        name: Wait for approval
        with:
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1

      - uses: actions/checkout@v3

      - name: Run a one-line script
        if: github.ref == 'refs/heads/"main"'
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${GITHUB_REF}
