# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  # manually 
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "feature & bugfix" branch
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

jobs:

  terraform:
    name: Terraform int/uat
    runs-on: ubuntu-latest
    env:
      TERRAFORM_ENVIRONMENT: 'devint'
    steps:
      - uses: actions/checkout@v3

      - name: Set TERRAFORM_WORKSPACE to uat for main
        if: github.ref == 'refs/heads/main'
        run: echo "TERRAFORM_ENVIRONMENT=uat" >> $GITHUB_ENV

      - name: Terraform Init
        run: 
          cd /private/${{ env.TERRAFORM_ENVIRONMENT }}/terraform
          terraform init
          terraform apply
          cd ../../../public/${{ env.TERRAFORM_ENVIRONMENT }}/terraform
          terraform init
          terraform apply

  terraform-prod:
    runs-on: ubuntu-latest
    name: Terraform prod
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v3

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Apply
        run: |
          cd /private/prod/terraform
          terraform init
          terraform apply
          cd ../../../public/prod/terraform
          terraform init
          terraform apply
