# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "dev"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TERRAFORM_WORKSPACE: 'dev'

jobs:

  terraform:
    name: Terraform int/uat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set TERRAFORM_WORKSPACE to uat of main
        if: github.ref == 'refs/heads/main'
        run: echo "TERRAFORM_WORKSPACE=uat" >> $GITHUB_ENV

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${GITHUB_REF}
          echo "${{ env.TERRAFORM_WORKSPACE }}"

  terraform-prod:
    runs-on: ubuntu-latest
    name: Terraform prod
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${GITHUB_REF}
